name: bees_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - imgaug
  - numpy<2.0
  - python=3.10
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pytorch-cuda=11.8
  - opencv
  - tqdm
  - Pillow
  - numba
  - pip
  - pip:
    - pycocotools
    - mmcv==2.2.0
    - --find-links https://download.openmmlab.com/mmcv/dist/cu118/torch2.1/index.html  # Changed to cu118
    - pytorch-lightning=2.4.0
    - wandb