# Image Preprocessing Parameters
image:
  mean: [0.408, 0.447, 0.470]
  std: [0.289, 0.274, 0.278]
  aspect_ratio: 0.75
  longer_side: 500

# Object Detection Parameters
detection:
  score_threshold: 0.51
  max_objects: 100
  valid_object_ids: [1]

model:
  backbone: 'res_18'

# Post-processing Correction Parameter
post_process:
  epsilon_correct_detection: 8  # in pixels

visualization:
  heatmap_max: 0.55 # max. heatmap temperature for better visualization